# Generated by Django 5.0.7 on 2024-07-31 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="brand",
            table="custom_brand_table",
        ),
        migrations.AlterModelTable(
            name="phone",
            table="custom_phone_table",
        ),
    ]
