# Generated by Django 5.0.7 on 2024-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_brand_table_alter_phone_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="phone",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available"), ("UNAVAILABLE", "Unavailable")],
                default="AVAILABLE",
                max_length=11,
            ),
        ),
    ]
