# Generated by Django 5.0.7 on 2024-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_phone_quantity_alter_phone_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('brand', 'model', 'color')},
        ),
    ]
